apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: togungbile
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/togungbile-harbor-project/db@sha256:b57bd4a343238ed5941beb22831e1b24c6eb54686a1466b4e41048e93b6c778e
        ports:
        - containerPort: 5432
